"""add insights column to publication

Revision ID: 453390925548
Revises: 094467b5f0a9
Create Date: 2025-10-04 21:48:06.677879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453390925548'
down_revision: Union[str, Sequence[str], None] = '094467b5f0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('normalized_text', sa.Text(), nullable=True))
    op.add_column('publication', sa.Column('insights', sa.Text(), nullable=True))
    op.add_column('triple', sa.Column('normalized_relation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triple', 'normalized_relation')
    op.drop_column('publication', 'insights')
    op.drop_column('entity', 'normalized_text')
    # ### end Alembic commands ###
